/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w2GXN278dkQ2gQTVQnPehW
// Component: pnV7KLVDUyoz

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextAreaInput from "../../components/plexus/TextAreaInput"; // plasmic-import: 0wwbx9l7LS5I/component
import { BaseTextArea } from "@plasmicpkgs/react-aria/skinny/registerTextArea";
import { inputHelpers as BaseTextArea_Helpers } from "@plasmicpkgs/react-aria/skinny/registerTextArea";
import IconButton from "../../components/widgets/IconButton"; // plasmic-import: LPry-TF4j22a/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: w2GXN278dkQ2gQTVQnPehW/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: w2GXN278dkQ2gQTVQnPehW/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import "./plasmic_plasmic_kit_data_binding.css"; // plasmic-import: w2GXN278dkQ2gQTVQnPehW/projectcss
import sty from "./PlasmicCopilotPromptInput.module.css"; // plasmic-import: pnV7KLVDUyoz/css

import PhotoSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__PhotoSvg"; // plasmic-import: BzQDBpjA9/icon
import ChevronDownSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: xZrB9_0ir/icon
import SendSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__SendSvg"; // plasmic-import: h2npYh74m/icon
import SpinnerIcon from "./icons/PlasmicIcon__Spinner"; // plasmic-import: EfDOV4MDLj/icon
import StopCircleIcon from "../plasmic_kit_icons/icons/PlasmicIcon__StopCircle"; // plasmic-import: zBYekuxyqPaj/icon

createPlasmicElementProxy;

export type PlasmicCopilotPromptInput__VariantMembers = {
  generating: "generating";
  loading: "loading";
  withAdminOverrides: "withAdminOverrides";
  dragState: "dragging" | "draggingOver";
  withImages: "withImages";
};
export type PlasmicCopilotPromptInput__VariantsArgs = {
  generating?: SingleBooleanChoiceArg<"generating">;
  loading?: SingleBooleanChoiceArg<"loading">;
  withAdminOverrides?: SingleBooleanChoiceArg<"withAdminOverrides">;
  dragState?: MultiChoiceArg<"dragging" | "draggingOver">;
  withImages?: SingleBooleanChoiceArg<"withImages">;
};
type VariantPropType = keyof PlasmicCopilotPromptInput__VariantsArgs;
export const PlasmicCopilotPromptInput__VariantProps =
  new Array<VariantPropType>(
    "generating",
    "loading",
    "withAdminOverrides",
    "dragState",
    "withImages"
  );

export type PlasmicCopilotPromptInput__ArgsType = { placeholder?: string };
type ArgPropType = keyof PlasmicCopilotPromptInput__ArgsType;
export const PlasmicCopilotPromptInput__ArgProps = new Array<ArgPropType>(
  "placeholder"
);

export type PlasmicCopilotPromptInput__OverridesType = {
  root?: Flex__<"div">;
  modelOverrideInput?: Flex__<typeof TextAreaInput>;
  systemPromptInput?: Flex__<typeof TextAreaInput>;
  textAreaInput?: Flex__<typeof BaseTextArea>;
  imageUploadIcon?: Flex__<typeof IconButton>;
  runPromptBtn?: Flex__<typeof IconButton>;
  stopBtn?: Flex__<typeof IconButton>;
  dropOverlay?: Flex__<"div">;
  span?: Flex__<"span">;
  imageUploadContainer?: Flex__<"div">;
};

export interface DefaultCopilotPromptInputProps {
  placeholder?: string;
  generating?: SingleBooleanChoiceArg<"generating">;
  loading?: SingleBooleanChoiceArg<"loading">;
  withAdminOverrides?: SingleBooleanChoiceArg<"withAdminOverrides">;
  dragState?: MultiChoiceArg<"dragging" | "draggingOver">;
  withImages?: SingleBooleanChoiceArg<"withImages">;
  className?: string;
}

const $$ = {};

function PlasmicCopilotPromptInput__RenderFunc(props: {
  variants: PlasmicCopilotPromptInput__VariantsArgs;
  args: PlasmicCopilotPromptInput__ArgsType;
  overrides: PlasmicCopilotPromptInput__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "generating",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.generating
      },
      {
        path: "modelOverrideInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props["defaultValue"]
      },
      {
        path: "systemPromptInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props["defaultValue"]
      },
      {
        path: "withAdminOverrides",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.withAdminOverrides
      },
      {
        path: "textAreaInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", BaseTextArea_Helpers)
      },
      {
        path: "dragState",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.dragState
      },
      {
        path: "loading",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.loading
      },
      {
        path: "withImages",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.withImages
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_w2GXN278dkQ2gQTVQnPehW",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootdragState_draggingOver]: hasVariant(
            $state,
            "dragState",
            "draggingOver"
          )
        }
      )}
    >
      <TextAreaInput
        data-plasmic-name={"modelOverrideInput"}
        data-plasmic-override={overrides.modelOverrideInput}

        autoResize={true}
        className={classNames("__wab_instance", sty.modelOverrideInput, {
          [sty.modelOverrideInputgenerating]: hasVariant(
            $state,
            "generating",
            "generating"
          ),
          [sty.modelOverrideInputwithAdminOverrides]: hasVariant(
            $state,
            "withAdminOverrides",
            "withAdminOverrides"
          )
        })}
        disabled={
          hasVariant($state, "generating", "generating") ? true : undefined
        }
        onChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "modelOverrideInput",
            "value"
          ]).apply(null, eventArgs);

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        placeholder={"Model provider override"}
        value={generateStateValueProp($state, ["modelOverrideInput", "value"])}
      />

      <TextAreaInput
        data-plasmic-name={"systemPromptInput"}
        data-plasmic-override={overrides.systemPromptInput}

        autoResize={true}
        className={classNames("__wab_instance", sty.systemPromptInput, {
          [sty.systemPromptInputgenerating]: hasVariant(
            $state,
            "generating",
            "generating"
          ),
          [sty.systemPromptInputwithAdminOverrides]: hasVariant(
            $state,
            "withAdminOverrides",
            "withAdminOverrides"
          )
        })}
        disabled={
          hasVariant($state, "generating", "generating") ? true : undefined
        }
        onChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "systemPromptInput",
            "value"
          ]).apply(null, eventArgs);

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        placeholder={"System prompt"}
        value={generateStateValueProp($state, ["systemPromptInput", "value"])}
      />

      <div
        className={classNames("all", sty.freeBox___1FAnc, {
          [sty.freeBoxgenerating___1FAnCakj9T]: hasVariant(
            $state,
            "generating",
            "generating"
          )
        })}
      >
        <div className={classNames("all", sty.freeBox__zdrEx)}>
          {(() => {
            const child$Props = {
              autoResize: true,
              className: classNames("__wab_instance", sty.textAreaInput, {
                [sty.textAreaInputgenerating]: hasVariant(
                  $state,
                  "generating",
                  "generating"
                ),
                [sty.textAreaInputloading]: hasVariant(
                  $state,
                  "loading",
                  "loading"
                ),
                [sty.textAreaInputwithAdminOverrides]: hasVariant(
                  $state,
                  "withAdminOverrides",
                  "withAdminOverrides"
                )
              }),
              onChange: async (...eventArgs: any) => {
                generateStateOnChangePropForCodeComponents(
                  $state,
                  "value",
                  ["textAreaInput", "value"],
                  BaseTextArea_Helpers
                ).apply(null, eventArgs);
              },
              placeholder: (() => {
                try {
                  return $props.placeholder;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })(),
              value: generateStateValueProp($state, ["textAreaInput", "value"])
            };
            initializeCodeComponentStates(
              $state,
              [
                {
                  name: "value",
                  plasmicStateName: "textAreaInput.value"
                }
              ],
              [],
              BaseTextArea_Helpers ?? {},
              child$Props
            );

            return (
              <BaseTextArea
                data-plasmic-name={"textAreaInput"}
                data-plasmic-override={overrides.textAreaInput}

                {...child$Props}
              />
            );
          })()}
        </div>
        <div
          className={classNames("all", sty.freeBox__ahFq, {
            [sty.freeBoxgenerating__ahFQakj9T]: hasVariant(
              $state,
              "generating",
              "generating"
            ),
            [sty.freeBoxloading__ahFQjtUxb]: hasVariant(
              $state,
              "loading",
              "loading"
            ),
            [sty.freeBoxwithAdminOverrides__ahFQiKnp6]: hasVariant(
              $state,
              "withAdminOverrides",
              "withAdminOverrides"
            )
          })}
        >
          <div className={classNames("all", sty.freeBox__pzPNk)}>
            <IconButton
              data-plasmic-name={"imageUploadIcon"}
              data-plasmic-override={overrides.imageUploadIcon}

              disabled={
                hasVariant($state, "loading", "loading")
                  ? true
                  : hasVariant($state, "generating", "generating")
                    ? true
                    : undefined
              }
              size={"medium"}
            >
              <PhotoSvgIcon
                className={classNames("all", sty.svg__ydJzA)}
                role={"img"}
              />
            </IconButton>
          </div>
          <div
            className={classNames("all", sty.freeBox__xruPv, {
              [sty.freeBoxgenerating__xruPvakj9T]: hasVariant(
                $state,
                "generating",
                "generating"
              )
            })}
          >
            {(hasVariant($state, "generating", "generating") ? false : true) ? (
              <IconButton
                data-plasmic-name={"runPromptBtn"}
                data-plasmic-override={overrides.runPromptBtn}

                disabled={
                  hasVariant($state, "loading", "loading") ? true : undefined
                }
                size={"medium"}
              >
                {(hasVariant($state, "loading", "loading") ? false : true) ? (
                  <SendSvgIcon
                    className={classNames("all", sty.svg__fr9AO, {
                      [sty.svgloading__fr9AOjtUxb]: hasVariant(
                        $state,
                        "loading",
                        "loading"
                      )
                    })}
                    role={"img"}
                  />
                ) : null}
                {(hasVariant($state, "loading", "loading") ? true : false) ? (
                  <SpinnerIcon
                    className={classNames("all", sty.svg__dGhou, {
                      [sty.svgloading__dGhoujtUxb]: hasVariant(
                        $state,
                        "loading",
                        "loading"
                      )
                    })}
                    role={"img"}
                  />
                ) : null}
              </IconButton>
            ) : null}
            <IconButton
              data-plasmic-name={"stopBtn"}
              data-plasmic-override={overrides.stopBtn}

              className={classNames("__wab_instance", sty.stopBtn, {
                [sty.stopBtngenerating]: hasVariant(
                  $state,
                  "generating",
                  "generating"
                ),
                [sty.stopBtnloading]: hasVariant($state, "loading", "loading")
              })}
              size={"medium"}
              type={[]}
            >
              <StopCircleIcon
                className={classNames("all", sty.svg__iUeqn)}
                role={"img"}
              />
            </IconButton>
          </div>
        </div>
        <div
          data-plasmic-name={"dropOverlay"}
          data-plasmic-override={overrides.dropOverlay}

          className={classNames("all", sty.dropOverlay, {
            [sty.dropOverlaydragState_draggingOver]: hasVariant(
              $state,
              "dragState",
              "draggingOver"
            ),
            [sty.dropOverlaydragState_dragging]: hasVariant(
              $state,
              "dragState",
              "dragging"
            )
          })}
        >
          <PhotoSvgIcon
            className={classNames("all", sty.svg__yuVHz, {
              [sty.svgdragState_draggingOver__yuVHzCz5Op]: hasVariant(
                $state,
                "dragState",
                "draggingOver"
              ),
              [sty.svgdragState_dragging__yuVHzo2NEr]: hasVariant(
                $state,
                "dragState",
                "dragging"
              )
            })}
            role={"img"}
          />

          <span
            data-plasmic-name={"span"}
            data-plasmic-override={overrides.span}

            className={classNames(
              "all",
              "span",
              "span__w2GXN",
              "__wab_text",
              sty.span,
              {
                [sty.spandragState_draggingOver]: hasVariant(
                  $state,
                  "dragState",
                  "draggingOver"
                ),
                [sty.spandragState_dragging]: hasVariant(
                  $state,
                  "dragState",
                  "dragging"
                )
              }
            )}
          >
            {"Drop image to attach"}
          </span>
        </div>
      </div>
      {(hasVariant($state, "withImages", "withImages") ? true : false) ? (
        <div
          data-plasmic-name={"imageUploadContainer"}
          data-plasmic-override={overrides.imageUploadContainer}

          className={classNames("all", sty.imageUploadContainer, {
            [sty.imageUploadContainerloading]: hasVariant(
              $state,
              "loading",
              "loading"
            ),
            [sty.imageUploadContainerwithImages]: hasVariant(
              $state,
              "withImages",
              "withImages"
            )
          })}
        />
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "modelOverrideInput",
    "systemPromptInput",
    "textAreaInput",
    "imageUploadIcon",
    "runPromptBtn",
    "stopBtn",
    "dropOverlay",
    "span",
    "imageUploadContainer"
  ],
  modelOverrideInput: ["modelOverrideInput"],
  systemPromptInput: ["systemPromptInput"],
  textAreaInput: ["textAreaInput"],
  imageUploadIcon: ["imageUploadIcon"],
  runPromptBtn: ["runPromptBtn"],
  stopBtn: ["stopBtn"],
  dropOverlay: ["dropOverlay", "span"],
  span: ["span"],
  imageUploadContainer: ["imageUploadContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  modelOverrideInput: typeof TextAreaInput;
  systemPromptInput: typeof TextAreaInput;
  textAreaInput: typeof BaseTextArea;
  imageUploadIcon: typeof IconButton;
  runPromptBtn: typeof IconButton;
  stopBtn: typeof IconButton;
  dropOverlay: "div";
  span: "span";
  imageUploadContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCopilotPromptInput__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCopilotPromptInput__VariantsArgs;
    args?: PlasmicCopilotPromptInput__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCopilotPromptInput__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCopilotPromptInput__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCopilotPromptInput__ArgProps,
          internalVariantPropNames: PlasmicCopilotPromptInput__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCopilotPromptInput__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCopilotPromptInput";
  } else {
    func.displayName = `PlasmicCopilotPromptInput.${nodeName}`;
  }
  return func;
}

export const PlasmicCopilotPromptInput = Object.assign(
  // Top-level PlasmicCopilotPromptInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    modelOverrideInput: makeNodeComponent("modelOverrideInput"),
    systemPromptInput: makeNodeComponent("systemPromptInput"),
    textAreaInput: makeNodeComponent("textAreaInput"),
    imageUploadIcon: makeNodeComponent("imageUploadIcon"),
    runPromptBtn: makeNodeComponent("runPromptBtn"),
    stopBtn: makeNodeComponent("stopBtn"),
    dropOverlay: makeNodeComponent("dropOverlay"),
    span: makeNodeComponent("span"),
    imageUploadContainer: makeNodeComponent("imageUploadContainer"),

    // Metadata about props expected for PlasmicCopilotPromptInput
    internalVariantProps: PlasmicCopilotPromptInput__VariantProps,
    internalArgProps: PlasmicCopilotPromptInput__ArgProps
  }
);

export default PlasmicCopilotPromptInput;
/* prettier-ignore-end */
