// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { TplCommentThread } from "@/wab/client/components/comments/utils";
import {
  DefaultThreadHistoryStatusProps,
  PlasmicThreadHistoryStatus,
} from "@/wab/client/plasmic/plasmic_kit_comments/PlasmicThreadHistoryStatus";
import { useStudioCtx } from "@/wab/client/studio-ctx/StudioCtx";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import * as React from "react";

export interface ThreadHistoryStatusProps
  extends DefaultThreadHistoryStatusProps {
  commentThread?: TplCommentThread;
}

function ThreadHistoryStatus_(
  props: ThreadHistoryStatusProps,
  ref: HTMLElementRefOf<"div">
) {
  const { commentThread, ...rest } = props;

  const studioCtx = useStudioCtx();
  const commentsCtx = studioCtx.commentsCtx;

  if (!commentThread) {
    return null;
  }

  return (
    <PlasmicThreadHistoryStatus
      root={{ ref }}
      {...rest}
      status={{
        onClick: async (e) => {
          e.stopPropagation();
          commentsCtx.editThread(commentThread.id, !commentThread.resolved);
        },
      }}
      resolved={commentThread.resolved}
    />
  );
}

export const ThreadHistoryStatus = React.forwardRef(ThreadHistoryStatus_);
