// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicButton,
} from "./plasmic/plain_kit/PlasmicButton";
import { PlumeButtonProps, PlumeButtonRef, usePlumeButton } from "@plasmicapp/plume";

interface ButtonProps extends PlumeButtonProps {
}

const Button = React.forwardRef(function Button(props: ButtonProps, ref: PlumeButtonRef) {
  const {plumeProps} = usePlumeButton(
    PlasmicButton,
    props,
    {
      isDisabledVariant: ["isDisabled", "isDisabled"],
      showStartIconVariant: ["withIcons", "start"],
      showEndIconVariant: ["withIcons", "end"],
      root: "root"
    },
    ref
  );
  return <PlasmicButton {...plumeProps} />;
});

export default Button;
