/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gtUDvxG6cmBbSzqLikNzoP
// Component: HtHxjHknmj_

import * as React from "react";

import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  Flex as Flex__,
  hasVariant,
  PlasmicIcon as PlasmicIcon__,
  renderPlasmicSlot,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  StrictProps,
  useDollarState,
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";

import Button from "../../components/widgets/Button"; // plasmic-import: SEF-sRmSoqV5c/component
import Textbox from "../../components/widgets/Textbox"; // plasmic-import: pA22NEzDCsn_/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: gtUDvxG6cmBbSzqLikNzoP/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import "./plasmic_plasmic_kit_optimize.css"; // plasmic-import: gtUDvxG6cmBbSzqLikNzoP/projectcss
import sty from "./PlasmicExperimentPanel.module.css"; // plasmic-import: HtHxjHknmj_/css

import ArrowRightSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ArrowRightSvg"; // plasmic-import: 9Jv8jb253/icon
import AwardSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__AwardSvg"; // plasmic-import: 4BNOoe_IX/icon
import ChevronDownSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: xZrB9_0ir/icon
import EditSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__EditSvg"; // plasmic-import: _Qa2gdunG/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: AKxTHEA6Rx/icon

createPlasmicElementProxy;

export type PlasmicExperimentPanel__VariantMembers = {
  isBase: "isBase";
  isEditing: "isEditing";
  type: "schedule" | "segment";
};
export type PlasmicExperimentPanel__VariantsArgs = {
  isBase?: SingleBooleanChoiceArg<"isBase">;
  isEditing?: SingleBooleanChoiceArg<"isEditing">;
  type?: SingleChoiceArg<"schedule" | "segment">;
};
type VariantPropType = keyof PlasmicExperimentPanel__VariantsArgs;
export const PlasmicExperimentPanel__VariantProps = new Array<VariantPropType>(
  "isBase",
  "isEditing",
  "type"
);

export type PlasmicExperimentPanel__ArgsType = {
  versionName?: React.ReactNode;
  controlContainer?: React.ReactNode;
};
type ArgPropType = keyof PlasmicExperimentPanel__ArgsType;
export const PlasmicExperimentPanel__ArgProps = new Array<ArgPropType>(
  "versionName",
  "controlContainer"
);

export type PlasmicExperimentPanel__OverridesType = {
  root?: Flex__<"div">;
  baseVersionIcon?: Flex__<"svg">;
  actionBtn?: Flex__<typeof Button>;
  variantNameRow?: Flex__<"div">;
  distribution2?: Flex__<"div">;
  control2?: Flex__<"div">;
  variantName2?: Flex__<"div">;
  variantName?: Flex__<typeof Textbox>;
  distribution?: Flex__<"div">;
  control?: Flex__<"div">;
  percentage?: Flex__<"div">;
  controlContainer?: Flex__<"div">;
  promoteBtn?: Flex__<typeof Button>;
};

export interface DefaultExperimentPanelProps {
  versionName?: React.ReactNode;
  controlContainer?: React.ReactNode;
  isBase?: SingleBooleanChoiceArg<"isBase">;
  isEditing?: SingleBooleanChoiceArg<"isEditing">;
  type?: SingleChoiceArg<"schedule" | "segment">;
  className?: string;
}

const $$ = {};

function PlasmicExperimentPanel__RenderFunc(props: {
  variants: PlasmicExperimentPanel__VariantsArgs;
  args: PlasmicExperimentPanel__ArgsType;
  overrides: PlasmicExperimentPanel__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants,
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isBase",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.isBase,
      },
      {
        path: "isEditing",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.isEditing,
      },
      {
        path: "type",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.type,
      },
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs,
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "all",
        "root_reset_gtUDvxG6cmBbSzqLikNzoP",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root,
        { [sty.rootisEditing]: hasVariant($state, "isEditing", "isEditing") }
      )}
    >
      <div className={classNames("all", sty.freeBox__kOw0R)}>
        <div
          className={classNames("all", sty.freeBox__cP6F, {
            [sty.freeBoxisBase__cP6FhIPlF]: hasVariant(
              $state,
              "isBase",
              "isBase"
            ),
          })}
        >
          <Icon4Icon
            data-plasmic-name={"baseVersionIcon"}
            data-plasmic-override={overrides.baseVersionIcon}
            className={classNames("all", sty.baseVersionIcon, {
              [sty.baseVersionIconisBase]: hasVariant(
                $state,
                "isBase",
                "isBase"
              ),
            })}
            role={"img"}
          />

          <div
            className={classNames("all", "__wab_text", sty.text__jOrxG, {
              [sty.textisBase__jOrxGhIPlF]: hasVariant(
                $state,
                "isBase",
                "isBase"
              ),
            })}
          >
            {"Original"}
          </div>
          {(hasVariant($state, "isBase", "isBase") ? false : true)
            ? renderPlasmicSlot({
                defaultContents: "Override",
                value: args.versionName,
                className: classNames(sty.slotTargetVersionName, {
                  [sty.slotTargetVersionNameisBase]: hasVariant(
                    $state,
                    "isBase",
                    "isBase"
                  ),
                  [sty.slotTargetVersionNameisEditing]: hasVariant(
                    $state,
                    "isEditing",
                    "isEditing"
                  ),
                }),
              })
            : null}
        </div>
        <div className={classNames("all", sty.freeBox__hPxO4)}>
          <Button
            data-plasmic-name={"actionBtn"}
            data-plasmic-override={overrides.actionBtn}
            className={classNames("__wab_instance", sty.actionBtn, {
              [sty.actionBtnisBase]: hasVariant($state, "isBase", "isBase"),
              [sty.actionBtnisEditing]: hasVariant(
                $state,
                "isEditing",
                "isEditing"
              ),
            })}
            endIcon={
              <ChevronDownSvgIcon
                className={classNames("all", sty.svg___6EEt)}
                role={"img"}
              />
            }
            size={"small"}
            startIcon={
              <ArrowRightSvgIcon
                className={classNames("all", sty.svg__kdMmN)}
                role={"img"}
              />
            }
            type={"secondary"}
          >
            <div
              className={classNames("all", sty.freeBox___5PG5, {
                [sty.freeBoxisEditing___5PG5P9Q9]: hasVariant(
                  $state,
                  "isEditing",
                  "isEditing"
                ),
              })}
            >
              <PlasmicIcon__
                PlasmicIconType={
                  hasVariant($state, "isEditing", "isEditing")
                    ? EditSvgIcon
                    : EditSvgIcon
                }
                className={classNames("all", sty.svg__gonUg, {
                  [sty.svgisEditing__gonUgP9Q9]: hasVariant(
                    $state,
                    "isEditing",
                    "isEditing"
                  ),
                })}
                role={"img"}
              />

              <div
                className={classNames("all", "__wab_text", sty.text__vZXyV, {
                  [sty.textisEditing__vZXyVp9Q9]: hasVariant(
                    $state,
                    "isEditing",
                    "isEditing"
                  ),
                })}
              >
                {hasVariant($state, "isEditing", "isEditing")
                  ? "Stop Editing"
                  : "Edit"}
              </div>
            </div>
          </Button>
        </div>
      </div>
      <div
        data-plasmic-name={"variantNameRow"}
        data-plasmic-override={overrides.variantNameRow}
        className={classNames("all", sty.variantNameRow, {
          [sty.variantNameRowisBase]: hasVariant($state, "isBase", "isBase"),
        })}
      >
        <div
          className={classNames("all", sty.freeBox___3B2Gh, {
            [sty.freeBoxisBase___3B2GhhIPlF]: hasVariant(
              $state,
              "isBase",
              "isBase"
            ),
          })}
        >
          <div
            data-plasmic-name={"distribution2"}
            data-plasmic-override={overrides.distribution2}
            className={classNames("all", "__wab_text", sty.distribution2, {
              [sty.distribution2isEditing]: hasVariant(
                $state,
                "isEditing",
                "isEditing"
              ),
            })}
          >
            {"Name"}
          </div>
        </div>
        <div
          data-plasmic-name={"control2"}
          data-plasmic-override={overrides.control2}
          className={classNames("all", sty.control2, {
            [sty.control2isBase]: hasVariant($state, "isBase", "isBase"),
          })}
        >
          <div
            data-plasmic-name={"variantName2"}
            data-plasmic-override={overrides.variantName2}
            className={classNames("all", "__wab_text", sty.variantName2)}
          >
            {"Variant Name"}
          </div>
          <Textbox
            data-plasmic-name={"variantName"}
            data-plasmic-override={overrides.variantName}
            className={classNames("__wab_instance", sty.variantName)}
            styleType={["white", "bordered"]}
            value={"Variant Name"}
          />
        </div>
      </div>
      <div
        className={classNames("all", sty.freeBox___8QuVy, {
          [sty.freeBoxisBase___8QuVyhIPlF]: hasVariant(
            $state,
            "isBase",
            "isBase"
          ),
          [sty.freeBoxtype_schedule___8QuVyJhGyh]: hasVariant(
            $state,
            "type",
            "schedule"
          ),
          [sty.freeBoxtype_schedule_isBase___8QuVyJhGyhHIPlF]:
            hasVariant($state, "isBase", "isBase") &&
            hasVariant($state, "type", "schedule"),
          [sty.freeBoxtype_segment___8QuVyRo3KZ]: hasVariant(
            $state,
            "type",
            "segment"
          ),
          [sty.freeBoxtype_segment_isBase___8QuVyRo3KZHIPlF]:
            hasVariant($state, "isBase", "isBase") &&
            hasVariant($state, "type", "segment"),
        })}
      >
        <div
          className={classNames("all", sty.freeBox__jruHn, {
            [sty.freeBoxisBase__jruHnhIPlF]: hasVariant(
              $state,
              "isBase",
              "isBase"
            ),
            [sty.freeBoxtype_schedule__jruHnJhGyh]: hasVariant(
              $state,
              "type",
              "schedule"
            ),
            [sty.freeBoxtype_schedule_isBase__jruHnJhGyhHIPlF]:
              hasVariant($state, "isBase", "isBase") &&
              hasVariant($state, "type", "schedule"),
            [sty.freeBoxtype_segment__jruHnRo3KZ]: hasVariant(
              $state,
              "type",
              "segment"
            ),
            [sty.freeBoxtype_segment_isBase__jruHnRo3KZHIPlF]:
              hasVariant($state, "isBase", "isBase") &&
              hasVariant($state, "type", "segment"),
          })}
        >
          <div
            data-plasmic-name={"distribution"}
            data-plasmic-override={overrides.distribution}
            className={classNames("all", "__wab_text", sty.distribution, {
              [sty.distributionisBase]: hasVariant($state, "isBase", "isBase"),
              [sty.distributionisEditing]: hasVariant(
                $state,
                "isEditing",
                "isEditing"
              ),
              [sty.distributiontype_schedule]: hasVariant(
                $state,
                "type",
                "schedule"
              ),
              [sty.distributiontype_segment]: hasVariant(
                $state,
                "type",
                "segment"
              ),
            })}
          >
            {hasVariant($state, "type", "segment")
              ? "Condition"
              : hasVariant($state, "type", "schedule")
              ? "Date range"
              : "Distribution"}
          </div>
        </div>
        <div
          data-plasmic-name={"control"}
          data-plasmic-override={overrides.control}
          className={classNames("all", sty.control, {
            [sty.controlisBase]: hasVariant($state, "isBase", "isBase"),
            [sty.controlisEditing]: hasVariant(
              $state,
              "isEditing",
              "isEditing"
            ),
            [sty.controltype_schedule]: hasVariant($state, "type", "schedule"),
            [sty.controltype_schedule_isBase]:
              hasVariant($state, "isBase", "isBase") &&
              hasVariant($state, "type", "schedule"),
            [sty.controltype_segment]: hasVariant($state, "type", "segment"),
            [sty.controltype_segment_isBase]:
              hasVariant($state, "isBase", "isBase") &&
              hasVariant($state, "type", "segment"),
          })}
        >
          <div
            className={classNames("all", sty.freeBox__ct5T, {
              [sty.freeBoxtype_schedule__ct5TJhGyh]: hasVariant(
                $state,
                "type",
                "schedule"
              ),
              [sty.freeBoxtype_segment__ct5TRo3KZ]: hasVariant(
                $state,
                "type",
                "segment"
              ),
            })}
          >
            <div
              data-plasmic-name={"percentage"}
              data-plasmic-override={overrides.percentage}
              className={classNames("all", "__wab_text", sty.percentage, {
                [sty.percentagetype_schedule]: hasVariant(
                  $state,
                  "type",
                  "schedule"
                ),
              })}
            >
              {"50%"}
            </div>
          </div>
          <div
            data-plasmic-name={"controlContainer"}
            data-plasmic-override={overrides.controlContainer}
            className={classNames("all", sty.controlContainer, {
              [sty.controlContainertype_schedule]: hasVariant(
                $state,
                "type",
                "schedule"
              ),
              [sty.controlContainertype_segment]: hasVariant(
                $state,
                "type",
                "segment"
              ),
            })}
          >
            {renderPlasmicSlot({
              defaultContents: null,
              value: args.controlContainer,
            })}
          </div>
        </div>
      </div>
      <div
        className={classNames("all", sty.freeBox__h3Dp, {
          [sty.freeBoxisBase__h3DphIPlF]: hasVariant(
            $state,
            "isBase",
            "isBase"
          ),
          [sty.freeBoxisEditing__h3DpP9Q9]: hasVariant(
            $state,
            "isEditing",
            "isEditing"
          ),
          [sty.freeBoxtype_schedule__h3DpJhGyh]: hasVariant(
            $state,
            "type",
            "schedule"
          ),
          [sty.freeBoxtype_segment__h3DpRo3KZ]: hasVariant(
            $state,
            "type",
            "segment"
          ),
        })}
      >
        <Button
          data-plasmic-name={"promoteBtn"}
          data-plasmic-override={overrides.promoteBtn}
          className={classNames("__wab_instance", sty.promoteBtn, {
            [sty.promoteBtnisBase]: hasVariant($state, "isBase", "isBase"),
            [sty.promoteBtnisEditing]: hasVariant(
              $state,
              "isEditing",
              "isEditing"
            ),
            [sty.promoteBtntype_schedule]: hasVariant(
              $state,
              "type",
              "schedule"
            ),
            [sty.promoteBtntype_segment]: hasVariant($state, "type", "segment"),
          })}
          endIcon={
            <ChevronDownSvgIcon
              className={classNames("all", sty.svg__vuSx4)}
              role={"img"}
            />
          }
          size={"small"}
          startIcon={
            <ArrowRightSvgIcon
              className={classNames("all", sty.svg___9ByMe)}
              role={"img"}
            />
          }
          type={"secondary"}
        >
          <div
            className={classNames("all", sty.freeBox__mHKW, {
              [sty.freeBoxisEditing__mHKWp9Q9]: hasVariant(
                $state,
                "isEditing",
                "isEditing"
              ),
            })}
          >
            <PlasmicIcon__
              PlasmicIconType={
                hasVariant($state, "isEditing", "isEditing")
                  ? AwardSvgIcon
                  : AwardSvgIcon
              }
              className={classNames("all", sty.svg___8Bs54, {
                [sty.svgisEditing___8Bs54P9Q9]: hasVariant(
                  $state,
                  "isEditing",
                  "isEditing"
                ),
              })}
              role={"img"}
            />

            <div
              className={classNames("all", "__wab_text", sty.text__bR9Ox, {
                [sty.textisEditing__bR9Oxp9Q9]: hasVariant(
                  $state,
                  "isEditing",
                  "isEditing"
                ),
              })}
            >
              {"Promote"}
            </div>
          </div>
        </Button>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "baseVersionIcon",
    "actionBtn",
    "variantNameRow",
    "distribution2",
    "control2",
    "variantName2",
    "variantName",
    "distribution",
    "control",
    "percentage",
    "controlContainer",
    "promoteBtn",
  ],
  baseVersionIcon: ["baseVersionIcon"],
  actionBtn: ["actionBtn"],
  variantNameRow: [
    "variantNameRow",
    "distribution2",
    "control2",
    "variantName2",
    "variantName",
  ],
  distribution2: ["distribution2"],
  control2: ["control2", "variantName2", "variantName"],
  variantName2: ["variantName2"],
  variantName: ["variantName"],
  distribution: ["distribution"],
  control: ["control", "percentage", "controlContainer"],
  percentage: ["percentage"],
  controlContainer: ["controlContainer"],
  promoteBtn: ["promoteBtn"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  baseVersionIcon: "svg";
  actionBtn: typeof Button;
  variantNameRow: "div";
  distribution2: "div";
  control2: "div";
  variantName2: "div";
  variantName: typeof Textbox;
  distribution: "div";
  control: "div";
  percentage: "div";
  controlContainer: "div";
  promoteBtn: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicExperimentPanel__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicExperimentPanel__VariantsArgs;
    args?: PlasmicExperimentPanel__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & // Specify variants directly as props
  Omit<PlasmicExperimentPanel__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicExperimentPanel__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicExperimentPanel__ArgProps,
          internalVariantPropNames: PlasmicExperimentPanel__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicExperimentPanel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicExperimentPanel";
  } else {
    func.displayName = `PlasmicExperimentPanel.${nodeName}`;
  }
  return func;
}

export const PlasmicExperimentPanel = Object.assign(
  // Top-level PlasmicExperimentPanel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    baseVersionIcon: makeNodeComponent("baseVersionIcon"),
    actionBtn: makeNodeComponent("actionBtn"),
    variantNameRow: makeNodeComponent("variantNameRow"),
    distribution2: makeNodeComponent("distribution2"),
    control2: makeNodeComponent("control2"),
    variantName2: makeNodeComponent("variantName2"),
    variantName: makeNodeComponent("variantName"),
    distribution: makeNodeComponent("distribution"),
    control: makeNodeComponent("control"),
    percentage: makeNodeComponent("percentage"),
    controlContainer: makeNodeComponent("controlContainer"),
    promoteBtn: makeNodeComponent("promoteBtn"),

    // Metadata about props expected for PlasmicExperimentPanel
    internalVariantProps: PlasmicExperimentPanel__VariantProps,
    internalArgProps: PlasmicExperimentPanel__ArgProps,
  }
);

export default PlasmicExperimentPanel;
/* prettier-ignore-end */
