/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gtUDvxG6cmBbSzqLikNzoP
// Component: QUkOz1f5TI

import * as React from "react";

import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  Flex as Flex__,
  StrictProps,
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";

import Button from "../../components/widgets/Button"; // plasmic-import: SEF-sRmSoqV5c/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: gtUDvxG6cmBbSzqLikNzoP/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import "./plasmic_plasmic_kit_optimize.css"; // plasmic-import: gtUDvxG6cmBbSzqLikNzoP/projectcss
import sty from "./PlasmicEditOverrideToggleButton.module.css"; // plasmic-import: QUkOz1f5TI/css

import ArrowRightSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ArrowRightSvg"; // plasmic-import: 9Jv8jb253/icon
import ChevronDownSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__ChevronDownSvg"; // plasmic-import: xZrB9_0ir/icon
import EditSvgIcon from "../plasmic_kit_icons/icons/PlasmicIcon__EditSvg"; // plasmic-import: _Qa2gdunG/icon

createPlasmicElementProxy;

export type PlasmicEditOverrideToggleButton__VariantMembers = {};
export type PlasmicEditOverrideToggleButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicEditOverrideToggleButton__VariantsArgs;
export const PlasmicEditOverrideToggleButton__VariantProps =
  new Array<VariantPropType>();

export type PlasmicEditOverrideToggleButton__ArgsType = {};
type ArgPropType = keyof PlasmicEditOverrideToggleButton__ArgsType;
export const PlasmicEditOverrideToggleButton__ArgProps =
  new Array<ArgPropType>();

export type PlasmicEditOverrideToggleButton__OverridesType = {
  root?: Flex__<typeof Button>;
  freeBox?: Flex__<"div">;
  text?: Flex__<"div">;
  componentName?: Flex__<"span">;
};

export interface DefaultEditOverrideToggleButtonProps {
  className?: string;
}

const $$ = {};

function PlasmicEditOverrideToggleButton__RenderFunc(props: {
  variants: PlasmicEditOverrideToggleButton__VariantsArgs;
  args: PlasmicEditOverrideToggleButton__ArgsType;
  overrides: PlasmicEditOverrideToggleButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants,
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <Button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
      endIcon={
        <ChevronDownSvgIcon
          className={classNames("all", sty.svg__vkCw5)}
          role={"img"}
        />
      }
      pointerCursor={true}
      size={"small"}
      startIcon={
        <ArrowRightSvgIcon
          className={classNames("all", sty.svg__heyIn)}
          role={"img"}
        />
      }
      type={"primary"}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames("all", sty.freeBox)}
      >
        <EditSvgIcon
          className={classNames("all", sty.svg__vi6F)}
          role={"img"}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames("all", "__wab_text", sty.text)}
        >
          <React.Fragment>
            <React.Fragment>{"Record Changes for "}</React.Fragment>
            {
              <span
                data-plasmic-name={"componentName"}
                data-plasmic-override={overrides.componentName}
                className={classNames(
                  "all",
                  "span",
                  "span__gtUDv",
                  "__wab_text",
                  "plasmic_default__inline",
                  sty.componentName
                )}
              >
                {"{ComponentName}"}
              </span>
            }
            <React.Fragment>{""}</React.Fragment>
          </React.Fragment>
        </div>
      </div>
    </Button>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "text", "componentName"],
  freeBox: ["freeBox", "text", "componentName"],
  text: ["text", "componentName"],
  componentName: ["componentName"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof Button;
  freeBox: "div";
  text: "div";
  componentName: "span";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEditOverrideToggleButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEditOverrideToggleButton__VariantsArgs;
    args?: PlasmicEditOverrideToggleButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & // Specify variants directly as props
  Omit<PlasmicEditOverrideToggleButton__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicEditOverrideToggleButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEditOverrideToggleButton__ArgProps,
          internalVariantPropNames:
            PlasmicEditOverrideToggleButton__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicEditOverrideToggleButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEditOverrideToggleButton";
  } else {
    func.displayName = `PlasmicEditOverrideToggleButton.${nodeName}`;
  }
  return func;
}

export const PlasmicEditOverrideToggleButton = Object.assign(
  // Top-level PlasmicEditOverrideToggleButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    text: makeNodeComponent("text"),
    componentName: makeNodeComponent("componentName"),

    // Metadata about props expected for PlasmicEditOverrideToggleButton
    internalVariantProps: PlasmicEditOverrideToggleButton__VariantProps,
    internalArgProps: PlasmicEditOverrideToggleButton__ArgProps,
  }
);

export default PlasmicEditOverrideToggleButton;
/* prettier-ignore-end */
