// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aukbrhkegRkQ6KizvhdUPT
// Component: JyqCOl0Ccj

import * as React from "react";

import {
  Flex as Flex__,
  SingleBooleanChoiceArg,
  StrictProps,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  renderPlasmicSlot,
  useDollarState,
  useTrigger,
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";

import ListItem from "../../components/ListItem"; // plasmic-import: v31d9_ANqk/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_plasmic_kit_design_system_deprecated_css from "../PP__plasmickit_design_system.module.css"; // plasmic-import: tXkSR39sgCDWSitZxC5xFV/projectcss
import projectcss from "../PP__plasmickit_left_pane.module.css"; // plasmic-import: aukbrhkegRkQ6KizvhdUPT/projectcss
import plasmic_plasmic_kit_color_tokens_css from "../plasmic_kit_q_4_color_tokens/plasmic_plasmic_kit_q_4_color_tokens.module.css"; // plasmic-import: 95xp9cYcv7HrNWpFWWhbcv/projectcss
import plasmic_plasmic_kit_new_design_system_former_style_controls_css from "../plasmic_kit_style_controls/plasmic_plasmic_kit_styles_pane.module.css"; // plasmic-import: gYEVvAzCcLMHDVPvuYxkFh/projectcss
import sty from "./PlasmicColorTokenControl.module.css"; // plasmic-import: JyqCOl0Ccj/css

import EyeIcon from "../plasmic_kit/PlasmicIcon__Eye"; // plasmic-import: A2FnGYgDh4e3U/icon
import ComponentsvgIcon from "../plasmic_kit_q_4_icons/icons/PlasmicIcon__Componentsvg"; // plasmic-import: vJVrKlrDD/icon

createPlasmicElementProxy;

export type PlasmicColorTokenControl__VariantMembers = {
  isDraggable: "isDraggable";
  isDragging: "isDragging";
};
export type PlasmicColorTokenControl__VariantsArgs = {
  isDraggable?: SingleBooleanChoiceArg<"isDraggable">;
  isDragging?: SingleBooleanChoiceArg<"isDragging">;
};
type VariantPropType = keyof PlasmicColorTokenControl__VariantsArgs;
export const PlasmicColorTokenControl__VariantProps =
  new Array<VariantPropType>("isDraggable", "isDragging");

export type PlasmicColorTokenControl__ArgsType = {
  children?: React.ReactNode;
  icon?: React.ReactNode;
  value?: React.ReactNode;
};
type ArgPropType = keyof PlasmicColorTokenControl__ArgsType;
export const PlasmicColorTokenControl__ArgProps = new Array<ArgPropType>(
  "children",
  "icon",
  "value"
);

export type PlasmicColorTokenControl__OverridesType = {
  root?: Flex__<"div">;
  listItem?: Flex__<typeof ListItem>;
  svg?: Flex__<"svg">;
};

export interface DefaultColorTokenControlProps {
  children?: React.ReactNode;
  icon?: React.ReactNode;
  value?: React.ReactNode;
  isDraggable?: SingleBooleanChoiceArg<"isDraggable">;
  isDragging?: SingleBooleanChoiceArg<"isDragging">;
  className?: string;
}

const $$ = {};

function PlasmicColorTokenControl__RenderFunc(props: {
  variants: PlasmicColorTokenControl__VariantsArgs;
  args: PlasmicColorTokenControl__ArgsType;
  overrides: PlasmicColorTokenControl__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isDraggable",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isDraggable,
      },
      {
        path: "isDragging",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isDragging,
      },
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs,
  });

  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover,
  };

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_plasmic_kit_design_system_deprecated_css.plasmic_tokens,
        plasmic_plasmic_kit_color_tokens_css.plasmic_tokens,
        plasmic_plasmic_kit_new_design_system_former_style_controls_css.plasmic_tokens,
        sty.root
      )}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <ListItem
        data-plasmic-name={"listItem"}
        data-plasmic-override={overrides.listItem}
        actions={
          <EyeIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={"img"}
          />
        }
        addendum={renderPlasmicSlot({
          defaultContents: "Blahblah",
          value: args.value,
        })}
        className={classNames("__wab_instance", sty.listItem, {
          [sty.listItemisDraggable]: hasVariant(
            $state,
            "isDraggable",
            "isDraggable"
          ),
          [sty.listItemisDragging]: hasVariant(
            $state,
            "isDragging",
            "isDragging"
          ),
        })}
        hasMenu={true}
        icon={renderPlasmicSlot({
          defaultContents: (
            <ComponentsvgIcon
              className={classNames(projectcss.all, sty.svg__oaVe8)}
              role={"img"}
            />
          ),

          value: args.icon,
        })}
        isDraggable={
          hasVariant($state, "isDraggable", "isDraggable") ? true : undefined
        }
        isDragging={
          hasVariant($state, "isDragging", "isDragging") ? true : undefined
        }
        showAddendums={triggers.hover_root ? true : undefined}
      >
        {renderPlasmicSlot({
          defaultContents: "Item name",
          value: args.children,
        })}
      </ListItem>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "listItem", "svg"],
  listItem: ["listItem", "svg"],
  svg: ["svg"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  listItem: typeof ListItem;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicColorTokenControl__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicColorTokenControl__VariantsArgs;
    args?: PlasmicColorTokenControl__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicColorTokenControl__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicColorTokenControl__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicColorTokenControl__ArgProps,
          internalVariantPropNames: PlasmicColorTokenControl__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicColorTokenControl__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicColorTokenControl";
  } else {
    func.displayName = `PlasmicColorTokenControl.${nodeName}`;
  }
  return func;
}

export const PlasmicColorTokenControl = Object.assign(
  // Top-level PlasmicColorTokenControl renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    listItem: makeNodeComponent("listItem"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicColorTokenControl
    internalVariantProps: PlasmicColorTokenControl__VariantProps,
    internalArgProps: PlasmicColorTokenControl__ArgProps,
  }
);

export default PlasmicColorTokenControl;
/* prettier-ignore-end */
