const postcss = require('rollup-plugin-postcss');
const styleInjectPath = require
  .resolve('style-inject/dist/style-inject.es')
  .replace(/[\\/]+/g, '/')
module.exports = {
  rollup(config, options) {
    config.plugins.push(
      postcss({
        inject: (varName, fileId) => {
          // Here, we make sure that the default styles are
          // injected at the _beginning_ of <head>, and the
          // component styles at the _end_.  Because examples-plain
          // may be used on other sites are also generated by Plasmic,
          // we want to make sure the default styles from examples-plain
          // don't override custom styles from other projects.
          if (fileId.includes("plasmic__default_style.css")) {
            return `
              import styleInject from '${styleInjectPath}';\n
              styleInject(${varName}, {insertAt: "top"});
              `;
            }  else {
              return `
              import styleInject from '${styleInjectPath}';\n
              styleInject(${varName});
            `;
          }
        }
      })
    );
    return config;
  },
};