// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kTSMroKPFv65RRTb44SCtk
// Component: l-sEnd6egOHM

import * as React from "react";

import {
  Flex as Flex__,
  StrictProps,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot,
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";

import UserListItem from "../../components/user-mentions/UserListItem"; // plasmic-import: w9CXWQAYB8kA/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_plasmic_kit_color_tokens_css from "../plasmic_kit_q_4_color_tokens/plasmic_plasmic_kit_q_4_color_tokens.module.css"; // plasmic-import: 95xp9cYcv7HrNWpFWWhbcv/projectcss
import plasmic_plasmic_kit_design_system_deprecated_css from "../PP__plasmickit_design_system.module.css"; // plasmic-import: tXkSR39sgCDWSitZxC5xFV/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: kTSMroKPFv65RRTb44SCtk/projectcss
import sty from "./PlasmicUserList.module.css"; // plasmic-import: l-sEnd6egOHM/css

createPlasmicElementProxy;

export type PlasmicUserList__VariantMembers = {};
export type PlasmicUserList__VariantsArgs = {};
type VariantPropType = keyof PlasmicUserList__VariantsArgs;
export const PlasmicUserList__VariantProps = new Array<VariantPropType>();

export type PlasmicUserList__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicUserList__ArgsType;
export const PlasmicUserList__ArgProps = new Array<ArgPropType>("children");

export type PlasmicUserList__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultUserListProps {
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function PlasmicUserList__RenderFunc(props: {
  variants: PlasmicUserList__VariantsArgs;
  args: PlasmicUserList__ArgsType;
  overrides: PlasmicUserList__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants,
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_plasmic_kit_design_system_deprecated_css.plasmic_tokens,
        plasmic_plasmic_kit_color_tokens_css.plasmic_tokens,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <React.Fragment>
            <UserListItem
              className={classNames("__wab_instance", sty.userListItem___9Fd6)}
              label={"John Doe"}
              value={"johndoe@example.com"}
            />

            <UserListItem
              className={classNames("__wab_instance", sty.userListItem__nWtDq)}
              label={"John Doe 2"}
              username={"John Doe 2"}
              value={"johndoe2@example.com"}
            />

            <UserListItem
              className={classNames("__wab_instance", sty.userListItem__wbQ8)}
              label={"John Doe 3"}
              username={"John Doe 3"}
              value={"johndoe3@example.com"}
            />
          </React.Fragment>
        ),
        value: args.children,
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUserList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUserList__VariantsArgs;
    args?: PlasmicUserList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUserList__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicUserList__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUserList__ArgProps,
          internalVariantPropNames: PlasmicUserList__VariantProps,
        }),
      [props, nodeName]
    );
    return PlasmicUserList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserList";
  } else {
    func.displayName = `PlasmicUserList.${nodeName}`;
  }
  return func;
}

export const PlasmicUserList = Object.assign(
  // Top-level PlasmicUserList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicUserList
    internalVariantProps: PlasmicUserList__VariantProps,
    internalArgProps: PlasmicUserList__ArgProps,
  }
);

export default PlasmicUserList;
/* prettier-ignore-end */
