export * from "./Data";
// export * from "./Embed";
// export { default as Embed } from "./Embed";
export * from "./Iframe";
export { default as Iframe } from "./Iframe";
export * from "./ScrollRevealer";
export { default as ScrollRevealer } from "./ScrollRevealer";
export * from "./Video";
export { default as Video } from "./Video";
export * from "./EmbedCss";
export { default as EmbedCss } from "./EmbedCss";
